// Code generated by scripts/sync-target-types.ts — DO NOT EDIT.
//
// Source of truth: src/data/targetTypeRegistry.ts
// Regenerate:      npx tsx scripts/sync-target-types.ts

package main

// SupportedTargetTypes lists all target types the host schema supports.
// Auto-generated from the frontend target type registry.
var SupportedTargetTypes = []string{
	"bluefield",
	"brocade",
	"cisco-mds",
	"dell-idrac",
	"docker",
	"emulex",
	"generic-http",
	"grafana",
	"infiniband",
	"kubernetes",
	"linux",
	"ndfc",
	"netapp-ontap",
	"nexus",
	"nutanix",
	"nvidia-sonic",
	"ollama",
	"open-webui",
	"powerflex",
	"powermax",
	"powerstore",
	"powerswitch",
	"prometheus",
	"proxmox",
	"pure-storage",
	"sonic-community",
	"truenas",
}
